@url = https://localhost:44368
@apiKey = 9e4a217c6f973c65e19867ad741e6c5b



### ---------------- get all counties ---------------- ###
POST {{url}}/api/hr/countries/get-all
Content-Type: application/json
apiKey: {{apiKey}}

{
  "skip": 0,
  "take": 10
}

### ---------------- get token ---------------- ###
POST {{url}}/api/hr/auth/get-token
Content-Type: application/json
apiKey: {{apiKey}}

{
  "username": "cyber-kemet",
  "password": "kemet"
}
### ---------------- get all counties ---------------- ###
### ---------------- get all counties ---------------- ###
### ---------------- get all counties ---------------- ###
### ---------------- get all counties ---------------- ###
### ---------------- get all counties ---------------- ###



